name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
      
    - name: Build and run tests
      run: mvn clean test

    - name: Generate Allure Reports
      run: mvn allure:report
        
    - name: Publish Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: target/allure-results
