name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
      
    - name: Build and run tests
      run: mvn clean test
      continue-on-error: true

    - name: Generate Allure Reports
      uses: simple-elf/allure-report-action@master
      id: allure-report
      with:
        allure_results: target/allure-results
        gh_pages: gh-pages
        allure_report: target/allure-report
        allure_history: target/allure-history

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: target/allure-report

    - name: Publish Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: target/allure-results
